
target 'marvel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for marvel

  target 'marvelTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SDWebImage', '~> 5.0'
pod 'NVActivityIndicatorView'

end
